# action.yml
name: "codacy-analysis-cli"
description: "Command line interface to execute Codacy code analysis locally"
inputs:
  directory:
    required: false
    default: "`pwd`"
  project-token:
    required: true
runs:
  using: "docker"
  image: "docker://codacy/codacy-analysis-cli:stable"
  args:
    - "analyse"
    - "--directory"
    - ${{ inputs.directory }}"
    - "--project-token"
    - "${{ inputs.project-token }}"
