files:
  - source: /content/**/*.md
    translation: /translations/%locale%/%original_path%/%original_file_name%
    ignore: [
      "/content/README.md"
    ]
  - source: /data/**/*.yml
    translation: /translations/%locale%/%original_path%/%original_file_name%
  - source: /data/**/*.md
    translation: /translations/%locale%/%original_path%/%original_file_name%
    ignore: [
      "data/README.md",
      "data/reusables/README.md",
      "data/variables/product.yml",
      "data/variables/README.md",
      "data/graphql",
      "data/products.yml"
      ]

# These end up as env vars used by the GitHub Actions workflow
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

# https://support.crowdin.com/configuration-file-v3/#saving-directory-structure-on-server
preserve_hierarchy: true